import { useRouter } from "next/router";
import { ArrowLeftIcon } from "@heroicons/react/outline";
import Head from "next/head";
import { Inter } from "next/font/google";
import CommentModal from "@/components/CommentModal";
import Sidebar from "@/components/Sidebar";
import Widgets from "@/components/Widgets";
import {
  collection,
  doc,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";
import { db } from "@/firebase";
import { useEffect, useState } from "react";
import Comment from "@/components/Comment";
import Post from "@/components/Post";

const inter = Inter({ subsets: ["latin"] });

export default function PostPage({ newsResults, randomUsersResults }) {
  const router = useRouter();
  const { id } = router.query; //Easily use query parameter value
  const [post, setPost] = useState();
  const [comments, setComments] = useState([]);

  // get the post data

  useEffect(
    () => onSnapshot(doc(db, "posts", id), (snapshot) => setPost(snapshot)),
    [db, id]
  );

  //get comments of the post

  useEffect(() => {
    onSnapshot(
      query(
        collection(db, "posts", id, "comments"),
        orderBy("timestamp", "desc")
      ),
      (snapshot) => setComments(snapshot.docs)
    );
  }, [db, id]);

  return (
    <>
      <div>
        <Head>
          <title>Post page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen mx-auto">
          {/* Sidebar */}
          <Sidebar />
          {/* Feed */}

          <div className="xl:ml-[370px] border-l border-r border-gray-200 xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl">
            <div className="flex items-center space-x-2 py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
              <div className="hoverEffect" onClick={() => router.push("/")}>
                <ArrowLeftIcon className="h-5" />
              </div>
              <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
                Tweet
              </h2>
            </div>

            <Post id={id} post={post} />

            {comments.length > 0 && (
              <div className="">
                {comments.map(
                  (
                    comment // showing all the comemnts here
                  ) => (
                    <Comment
                      key={comment.id}
                      id={comment.id}
                      originalPostId={id}
                      commentId={comment.id}   // Added by Sam and diff from the video
                      comment={comment.data()}
                    />
                  )
                )}
              </div>
            )}
          </div>

          {/* Widgets */}
          <Widgets newsResults={newsResults.articles} />
          {/* Modal */}
          <CommentModal />
        </main>
      </div>
    </>
  );
}

//https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());

  return {
    props: {
      newsResults,
    },
  };
}
