import Head from "next/head";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import Feed from "@/components/Feed";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <div>
        {" "}
        <Head>
          <title>Accounting App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" /> 
          </Head>
          <main className="flex min-h-screen max-w-7x1 mx-auto">
            {/* Sidebar */}
            <Sidebar />
            {/* Feed */}
            <Feed/>
            {/* Widgets */}
            {/* Modal */}
          </main>
       
      </div>
    </>
  );
}
